ENTITIES = [
    {
        "name": "Prędkość sprężarki w trybie nocnym",
        "register": 263,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "name": "Prędkość wentylatora w trybie nocnym",
        "register": 264,
        "min": 0,
        "max": 1000,
        "step": 1,
        "icon": "mdi:fan",
    },
    {
        "name": "Funkcja czasowa rok",
        "register": 182,
        "min": 0,
        "max": 99,
        "step": 1,
        "unit": "y",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa miesiąc",
        "register": 183,
        "min": 0,
        "max": 12,
        "step": 1,
        "unit": "m",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa dzień",
        "register": 184,
        "min": 0,
        "max": 31,
        "step": 1,
        "unit": "d",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa godzina",
        "register": 185,
        "min": 0,
        "max": 23,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa minuta",
        "register": 186,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa dzień tygodnia",
        "register": 187,
        "min": 0,
        "max": 7,
        "step": 1,
        "unit": "d",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa poniedziałek godzina włączenia",
        "register": 218,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa poniedziałek minuta włączenia",
        "register": 219,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa poniedziałek godzina wyłączenia",
        "register": 232,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa poniedziałek minuta wyłączenia",
        "register": 233,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa wtorek godzina włączenia",
        "register": 220,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa wtorek minuta włączenia",
        "register": 221,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa wtorek godzina wyłączenia",
        "register": 234,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa wtorek minuta wyłączenia",
        "register": 235,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa środa godzina włączenia",
        "register": 222,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa środa minuta włączenia",
        "register": 223,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa środa godzina wyłączenia",
        "register": 236,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa środa minuta wyłączenia",
        "register": 237,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa czwartek godzina wlączenia",
        "register": 224,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa czwartek minuta wlączenia",
        "register": 225,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa czwartek godzina wyłączenia",
        "register": 238,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa czwartek minuta wyłączenia",
        "register": 239,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa piątek godzina włączenia",
        "register": 226,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa piątek minuta włączenia",
        "register": 227,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa piątek godzina wyłączenia",
        "register": 240,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa piątek minuta wyłączenia",
        "register": 241,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa sobota godzina włączenia",
        "register": 228,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa sobota minuta włączenia",
        "register": 229,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa sobota godzina wyłączenia",
        "register": 242,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa sobota minuta wyłączenia",
        "register": 243,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa niedziela godzina włączenia",
        "register": 230,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa niedziela minuta włączenia",
        "register": 231,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa niedziela godzina wyłączenia",
        "register": 244,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa niedziela minuta wyłączenia",
        "register": 245,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa godź X1",
        "register": 246,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa min X1",
        "register": 247,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa godź X2",
        "register": 250,
        "min": 0,
        "max": 95,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa min X2",
        "register": 251,
        "min": 0,
        "max": 131,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa godź X3",
        "register": 254,
        "min": 0,
        "max": 167,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa min X3",
        "register": 255,
        "min": 0,
        "max": 203,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa godź X4",
        "register": 258,
        "min": 0,
        "max": 259,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Funkcja czasowa min X4",
        "register": 259,
        "min": 0,
        "max": 275,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Minimalna nastawa chłodzenia",
        "register": 72,
        "min": -99,
        "max": 100,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "name": "Maksymalna nastawa chłodzenia",
        "register": 72,
        "min": -99,
        "max": 100,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
]
