ENTITIES = [
    {
        "name": "Podgrzewacz sprężarki",
        "register": 1,
        "icon_on": "mdi:radiator",
        "icon_off": "mdi:radiator-disabled",
        "write_type": "coil",
    },
    {
        "name": "Auto start",
        "register": 2,
        "write_type": "coil",
    },
    {
        "name": "Manualne wprowadzenie parametrów BLCD",
        "register": 14,
        "icon": "mdi:tune",
        "write_type": "coil",
    },
    {
        "name": "Network EN",
        "register": 34,
        "write_type": "coil",
    },
    {
        "name": "Defrost",
        "register": 36,
        "icon_on": "mdi:snowflake-melt",
        "icon_off": "mdi:snowflake-off",
        "write_type": "coil",
    },
    {
        "name": "Funkcja czasowa: Plan tygodniowy",
        "register": 38,
        "icon_on": "mdi:timer-check",
        "icon_off": "mdi:timer-off",
        "write_type": "coil",
    },
    {
        "name": "Funkcja czasowa: Plan godzinowy",
        "register": 39,
        "icon_on": "mdi:timer-check",
        "icon_off": "mdi:timer-off",
        "write_type": "coil",
    },
    {
        "name": "Włączanie pompy",
        "register": 40,
        "icon_on": "mdi:heat-pump",
        "icon_off": "mdi:heat-pump-offline",
        "write_type": "coil",
    },
    {
        "name": "Tryb CWU",
        "register": 42,
        "write_type": "coil",
    },
    {
        "name": "Automatyczne przełączanie pomiędzy ogrzewaniem a chłodzeniem",
        "register": 47,
        "write_type": "coil",
    },
    {
        "name": "Ambient temperature switch",
        "register": 52,
        "icon_on": "mdi:home-thermometer",
        "icon_off": "mdi:home-thermometer-outline",
        "write_type": "coil",
    },
]
