NUMBERS = [
    {
        "unique_id": "predkosc_sprezarki_w_trybie_nocnym",
        "name": "Prędkość sprężarki w trybie nocnym",
        "register": 263,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_wentylatora_w_trybie_nocnym",
        "name": "Prędkość wentylatora w trybie nocnym",
        "register": 264,
        "min": 0,
        "max": 1000,
        "step": 1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "funkcja_czasowa_rok",
        "name": "Funkcja czasowa rok",
        "register": 182,
        "min": 0,
        "max": 99,
        "step": 1,
        "unit": "y",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_miesiac",
        "name": "Funkcja czasowa miesiąc",
        "register": 183,
        "min": 0,
        "max": 12,
        "step": 1,
        "unit": "m",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_dzien",
        "name": "Funkcja czasowa dzień",
        "register": 184,
        "min": 0,
        "max": 31,
        "step": 1,
        "unit": "d",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_godzina",
        "name": "Funkcja czasowa godzina",
        "register": 185,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_minuta",
        "name": "Funkcja czasowa minuta",
        "register": 186,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_dzien_tygodnia",
        "name": "Funkcja czasowa dzień tygodnia",
        "register": 187,
        "min": 0,
        "max": 7,
        "step": 1,
        "unit": "d",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_poniedzialek_godzina_wlaczenia",
        "name": "Funkcja czasowa poniedziałek godzina włączenia",
        "register": 218,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_poniedzialek_minuta_wlaczenia",
        "name": "Funkcja czasowa poniedziałek minuta włączenia",
        "register": 219,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_poniedzialek_godzina_wylaczenia",
        "name": "Funkcja czasowa poniedziałek godzina wyłączenia",
        "register": 232,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_poniedzialek_minuta_wylaczenia",
        "name": "Funkcja czasowa poniedziałek minuta wyłączenia",
        "register": 233,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_wtorek_godzina_wlaczenia",
        "name": "Funkcja czasowa wtorek godzina włączenia",
        "register": 220,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_wtorek_minuta_wlaczenia",
        "name": "Funkcja czasowa wtorek minuta włączenia",
        "register": 221,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_wtorek_godzina_wylaczenia",
        "name": "Funkcja czasowa wtorek godzina wyłączenia",
        "register": 234,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_wtorek_minuta_wylaczenia",
        "name": "Funkcja czasowa wtorek minuta wyłączenia",
        "register": 235,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sroda_godzina_wlaczenia",
        "name": "Funkcja czasowa środa godzina włączenia",
        "register": 222,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sroda_minuta_wlaczenia",
        "name": "Funkcja czasowa środa minuta włączenia",
        "register": 223,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sroda_godzina_wylaczenia",
        "name": "Funkcja czasowa środa godzina wyłączenia",
        "register": 236,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sroda_minuta_wylaczenia",
        "name": "Funkcja czasowa środa minuta wyłączenia",
        "register": 237,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_czwartek_godzina_wlaczenia",
        "name": "Funkcja czasowa czwartek godzina wlączenia",
        "register": 224,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_czwartek_minuta_wlaczenia",
        "name": "Funkcja czasowa czwartek minuta wlączenia",
        "register": 225,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_czwartek_godzina_wylaczenia",
        "name": "Funkcja czasowa czwartek godzina wyłączenia",
        "register": 238,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_czwartek_minuta_wylaczenia",
        "name": "Funkcja czasowa czwartek minuta wyłączenia",
        "register": 239,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_piatek_godzina_wlaczenia",
        "name": "Funkcja czasowa piątek godzina włączenia",
        "register": 226,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_piatek_minuta_wlaczenia",
        "name": "Funkcja czasowa piątek minuta włączenia",
        "register": 227,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_piatek_godzina_wylaczenia",
        "name": "Funkcja czasowa piątek godzina wyłączenia",
        "register": 240,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_piatek_minuta_wylaczenia",
        "name": "Funkcja czasowa piątek minuta wyłączenia",
        "register": 241,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sobota_godzina_wlaczenia",
        "name": "Funkcja czasowa sobota godzina włączenia",
        "register": 228,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sobota_minuta_wlaczenia",
        "name": "Funkcja czasowa sobota minuta włączenia",
        "register": 229,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sobota_godzina_wylaczenia",
        "name": "Funkcja czasowa sobota godzina wyłączenia",
        "register": 242,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_sobota_minuta_wylaczenia",
        "name": "Funkcja czasowa sobota minuta wyłączenia",
        "register": 243,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_niedziela_godzina_wlaczenia",
        "name": "Funkcja czasowa niedziela godzina włączenia",
        "register": 230,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_niedziela_minuta_wlaczenia",
        "name": "Funkcja czasowa niedziela minuta włączenia",
        "register": 231,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_niedziela_godzina_wylaczenia",
        "name": "Funkcja czasowa niedziela godzina wyłączenia",
        "register": 244,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_niedziela_minuta_wylaczenia",
        "name": "Funkcja czasowa niedziela minuta wyłączenia",
        "register": 245,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_godz_x1",
        "name": "Funkcja czasowa godź X1",
        "register": 246,
        "min": 0,
        "max": 23,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_min_x1",
        "name": "Funkcja czasowa min X1",
        "register": 247,
        "min": 0,
        "max": 59,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_godz_x2",
        "name": "Funkcja czasowa godź X2",
        "register": 250,
        "min": 0,
        "max": 95,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_min_x2",
        "name": "Funkcja czasowa min X2",
        "register": 251,
        "min": 0,
        "max": 131,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_godz_x3",
        "name": "Funkcja czasowa godź X3",
        "register": 254,
        "min": 0,
        "max": 167,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_min_x3",
        "name": "Funkcja czasowa min X3",
        "register": 255,
        "min": 0,
        "max": 203,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_godz_x4",
        "name": "Funkcja czasowa godź X4",
        "register": 258,
        "min": 0,
        "max": 259,
        "step": 1,
        "unit": "h",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "funkcja_czasowa_min_x4",
        "name": "Funkcja czasowa min X4",
        "register": 259,
        "min": 0,
        "max": 275,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "minimalna_nastawa_chlodzenia",
        "name": "Minimalna nastawa chłodzenia",
        "register": 72,
        "min": -99,
        "max": 100,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "maksymalna_nastawa_chlodzenia",
        "name": "Maksymalna nastawa chłodzenia",
        "register": 73,
        "min": -99,
        "max": 100,
        "step": 1,
        "unit": "max",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "adres",
        "name": "Adres",
        "register": 74,
        "min": 1,
        "max": 207,
        "step": 1,
    },
    {
        "unique_id": "opoznienie_zalaczenia_sprezarki",
        "name": "Opóźnienie załączenia sprężarki",
        "register": 13,
        "min": 0,
        "max": 999,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "ambient_temperature_switch",
        "name": "Ambient switch setpoint",
        "register": 297,
        "min": 10,
        "max": 30,
        "step": 1,
        "unit": "min",
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "minimalny_czas_postoju_sprezarki",
        "name": "Minimalny czas postoju sprężarki",
        "register": 299,
        "min": 1,
        "max": 99,
        "step": 1,
        "icon": "mdi:timer-edit",
    },
    {
        "unique_id": "temperatura_wyswietlacza_offset",
        "name": "Temperatura wyświetlacza offset",
        "register": 300,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temperatura_zasilania_offset",
        "name": "Temperatura zasilania offset",
        "register": 301,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temperatura_zewnetrzna_offset",
        "name": "Temperatura zewnętrzna offset",
        "register": 302,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temperatura_tloczenia_offset",
        "name": "Temperatura tłoczenia offset",
        "register": 303,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temperatura_ssania_offset",
        "name": "Temperatura ssania offset",
        "register": 304,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "czujnik_wysokiego_cisnienia",
        "name": "Czujnik wysokiego ciśnienia",
        "register": 305,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:gauge",
    },
    {
        "unique_id": "czujnik_niskiego_cisnienia",
        "name": "Czujnik niskiego ciśnienia",
        "register": 306,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:gauge",
    },
    {
        "unique_id": "temperatura_cwu_offset",
        "name": "Temperatura CWU offset",
        "register": 307,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temperatura_parownika_offset",
        "name": "Temperatura parownika offset",
        "register": 308,
        "min": 0,
        "max": 99,
        "step": 1,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "ustaw_nowe_haslo_serwisowe",
        "name": "Ustaw nowe hasło serwisowe",
        "register": 76,
        "min": 0,
        "max": 9999,
        "step": 1,
        "mode": "box",
        "icon": "mdi:lock-reset",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_4_do_9",
        "name": "Prędkość sprężarki 4<Temperatura zewnętrzna<=9",
        "register": 265,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_minus_3_do_4",
        "name": "Prędkość sprężarki -3<Temperatura zewnętrzna<=4",
        "register": 266,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_minus_9_do_minus_3",
        "name": "Prędkość sprężarki -9<Temperatura zewnętrzna<=-3",
        "register": 267,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_minus_15_do_minus_9",
        "name": "Prędkość sprężarki -15<Temperatura zewnętrzna<=-9",
        "register": 268,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_ponizej_minus_15",
        "name": "Prędkość sprężarki Temperatura zewnętrzna <=-15",
        "register": 269,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_powyzej_9",
        "name": "Prędkość sprężarki 9<Temperatura zewnętrzna",
        "register": 270,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_powyzej_38",
        "name": "Prędkość sprężarki 38<Temperatura zewnętrzna",
        "register": 271,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_powyzej_33_ponizej_38",
        "name": "Prędkość sprężarki 33<Temperatura zewnętrzna<=38",
        "register": 272,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_powyzej_30_ponizej_33",
        "name": "Prędkość sprężarki 30<Temperatura zewnętrzna<=33",
        "register": 273,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_26_do_30",
        "name": "Prędkość sprężarki 26<Temperatura zewnętrzna<=30",
        "register": 274,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "predkosc_sprezarki_gdy_temperatura_zewnetrzna_ponizej_26",
        "name": "Prędkość sprężarki temperatura zewnętrzna<=26",
        "register": 275,
        "min": 0,
        "max": 80,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "defrost_minimalna_predkosc_sprezarki_%",
        "name": "Defrost minimalna prędkość sprężarki %",
        "register": 77,
        "min": 0,
        "max": 90,
        "step": 1,
        "icon": "mdi:bag-personal",
    },
    {
        "unique_id": "defrost_docelowe_otwarcie_zaworu_eev",
        "name": "Defrost docelowe otwarcie zaworu EEV",
        "register": 78,
        "min": 0,
        "max": 480,
        "step": 1,
        "unit": "steps",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_otwarcie_zaworu_eev_po_zakonczeniu",
        "name": "Defrost otwarcie zaworu EEV po zakończeniu",
        "register": 79,
        "min": 0,
        "max": 480,
        "step": 1,
        "unit": "steps",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_czas_otwarcia_zaworu_eev",
        "name": "Defrost czas otwarcia zaworu EEV",
        "register": 80,
        "min": 0,
        "max": 999,
        "step": 1,
        "unit": "s",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_docelowa_predkosc_sprezarki_podczas_odszraniania",
        "name": "Defrost docelowa prędkość sprężarki podczas odszraniania",
        "register": 81,
        "min": 30,
        "max": 120,
        "step": 1,
        "unit": "hz",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_predkosc_pompy_obiegowej",
        "name": "Defrost prędkość pompy obiegowej",
        "register": 82,
        "min": 30,
        "max": 120,
        "step": 1,
        "unit": "%",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_temperatura_parownika_przy_ktorej_rozpoczyna_sie_odszranianie",
        "name": "Defrost temperatura parownika, przy której rozpoczyna się odszranianie",
        "register": 83,
        "min": -20,
        "max": 30,
        "step": 1,
        "unit": "°C",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_temperatura_parownika_przy_ktorej_konczy_sie_odszranianie",
        "name": "Defrost temperatura parownika, przy której kończy się odszranianie",
        "register": 84,
        "min": 0,
        "max": 30,
        "step": 1,
        "unit": "°C",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_temperatura_zewnetrzna_dla_uruchomienia_odszraniania",
        "name": "Defrost temperatura zewnętrzna dla uruchomienia odszraniania",
        "register": 85,
        "min": -30,
        "max": 30,
        "step": 1,
        "unit": "°C",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_min_roznica_miedzy_powietrzem_a_parownikiem_wymagana_do_odszraniania",
        "name": "Defrost min różnica temp między powietrzem a parownikiem wymagana do odszraniania",
        "register": 86,
        "min": 1,
        "max": 30,
        "step": 1,
        "unit": "°C",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_opoznienie_rozpoczecia_odszraniania",
        "name": "Defrost opóźnienie rozpoczęcia odszraniania",
        "register": 87,
        "min": 0,
        "max": 90,
        "step": 1,
        "unit": "min",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_minimalny_czas",
        "name": "Defrost minimalny czas",
        "register": 88,
        "min": 1,
        "max": 99,
        "step": 1,
        "unit": "min",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_maksymalny_czas",
        "name": "Defrost maksymalny czas",
        "register": 89,
        "min": 1,
        "max": 99,
        "step": 1,
        "unit": "min",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_interwal_odszraniania",
        "name": "Defrost interwał odszraniania",
        "register": 90,
        "min": 0,
        "max": 490,
        "step": 1,
        "unit": "min",
        "icon": "mdi:snowflake-melt",
    },
    {
        "unique_id": "defrost_wymuszone_odszranianie_co",
        "name": "Defrost wymuszone odszranianie co",
        "register": 91,
        "min": 0,
        "max": 999,
        "step": 1,
        "unit": "min",
        "icon": "mdi:snowflake-melt",
    },
]
DATA = NUMBERS
