SENSORS = [
    {
        "unique_id": "d07_zaw_3_drog",
        "name": "Zawór trójdrogowy pozycja",
        "register": 11,
        "icon": "mdi:valve-open",
        "mapping": {
            1: "C.W.U.",
            2: "C.O.",
        },
        "icon_map": {
            1: "mdi:valve-open",
            2: "mdi:valve-closed",
        },
    },
    {
        "unique_id": "temp_powrotu",
        "name": "Temperatura powrotu",
        "register": 188,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temp_zasilania",
        "name": "Temperatura zasilania",
        "register": 189,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temp_zewnetrzna",
        "name": "Temperatura zewnętrzna",
        "register": 190,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temp_sprezania",
        "name": "Temperatura sprężania",
        "register": 191,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temp_ssania",
        "name": "Temperatura ssania",
        "register": 192,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "cisnienie_sprezania",
        "name": "Ciśnienie sprężania",
        "register": 193,
        "unit": "bar",
        "device_class": "pressure",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:gauge",
        "description": "Na sterowniku w zakładce Parametry, pod nazwą B6: Cis.po stronie tłocznej.",
    },
    {
        "unique_id": "cisnienie_ssania",
        "name": "Ciśnienie ssania",
        "register": 194,
        "unit": "bar",
        "device_class": "pressure",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:gauge",
    },
    {
        "unique_id": "temp_cwu",
        "name": "Temperatura CWU",
        "register": 195,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "temp_parownika",
        "name": "Temperatura parownika",
        "register": 196,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:thermometer",
    },
    {
        "unique_id": "y1_wentylator",
        "name": "Y1 Wentylator",
        "register": 197,
        "unit": "%",
        "scale": 0.1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "y3_pompa_obieg",
        "name": "Y3 Pompa obiegowa",
        "register": 198,
        "unit": "%",
        "device_class": "none",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:pump",
    },
    {
        "unique_id": "dc_fan_1_output",
        "name": "Wentylator 1 sterowanie",
        "register": 199,
        "unit": "rpm",
        "scale": 1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "dc_fan_1_feedback",
        "name": "Wentylator 1 pomiar",
        "register": 202,
        "unit": "rpm",
        "scale": 1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "dc_fan_2_output",
        "name": "Wentylator 2 sterowanie",
        "register": 201,
        "unit": "rpm",
        "scale": 1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "dc_fan_2_feedback",
        "name": "Wentylator 2 pomiar",
        "register": 200,
        "unit": "rpm",
        "scale": 1,
        "icon": "mdi:fan",
    },
    {
        "unique_id": "wymagana_wydajnosc",
        "name": "Wymagana wydajność",
        "register": 203,
        "unit": "%",
        "scale": 0.1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "aktualna_wymagana_wydajnosc",
        "name": "Aktualna wymagana wydajność",
        "register": 204,
        "unit": "%",
        "scale": 0.1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "obroty_sprezarki",
        "name": "Obroty sprężarki",
        "register": 205,
        "unit": "rps",
        "scale": 0.1,
        "icon": "mdi:rotate-right",
    },
    {
        "unique_id": "zawor_eev",
        "name": "Zawór EEV",
        "register": 207,
        "unit": "%",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:valve",
    },
    {
        "unique_id": "status_2",
        "name": "Status 2",
        "register": 209,
        "scale": 1,
        "icon": "mdi:information",
        "mapping": {
            0: "OK",
            1: "Sterowanie",
            2: "Graniczny",
        },
        "icon_map": {
            0: "mdi:check-circle",
            1: "mdi:remote",
            2: "mdi:alert",
        },
    },
    {
        "unique_id": "zabezpieczenie",
        "name": "Zabezpieczenie",
        "register": 210,
        "scale": 1,
        "icon": "mdi:information",
        "mapping": {
            0: "OK",
            1: "OK",
            2: "Niskie przegrzanie",
            3: "Niskie ciśnienie",
            4: "Wysokie ciśnienie",
            5: "Wysoka temp skraplacza",
        },
        "icon_map": {
            0: "mdi:check-circle",
            1: "mdi:check-circle",
            2: "mdi:alert",
            3: "mdi:alert",
            4: "mdi:alert",
            5: "mdi:alert",
        },
    },
    {
        "unique_id": "przegrzanie",
        "name": "Temperatura przegrzania",
        "register": 211,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:coolant-temperature",
    },
    {
        "unique_id": "tryb_pracy_pompy",
        "name": "Tryb pracy pompy",
        "register": 215,
        "scale": 1,
        "icon": "mdi:information",
        "mapping": {
            0: "Chłodzenie",
            1: "Ogrzewanie",
            2: "CWU",
        },
        "icon_map": {
            0: "mdi:snowflake",
            1: "mdi:radiator",
            2: "mdi:shower",
        },
    },
    {
        "unique_id": "temp_tloczenia",
        "name": "Temperatura tłoczenia",
        "register": 216,
        "unit": "°C",
        "device_class": "temperature",
        "state_class": "measurement",
        "scale": 0.1,
        "signed": True,
        "icon": "mdi:coolant-temperature",
    },
    {
        "unique_id": "status",
        "name": "Status",
        "register": 217,
        "scale": 1,
        "icon": "mdi:information",
        "mapping": {
            0: "Przygotowanie",
            1: "Praca",
            2: "Stop Alarm",
            3: "Stop timer",
            4: "Stop obsługa",
            5: "Stop Sterowanie",
            6: "Stop",
            7: "Tryb ręczny",
            8: "Antyzamarzanie",
            9: "Stop AC linkage",
            10: "Zmiana trybu",
        },
        "icon_map": {
            0: "mdi:information",
            1: "mdi:run",
            2: "mdi:stop",
            3: "mdi:timer-off",
            4: "mdi:account-wrench",
            5: "mdi:remote",
            6: "mdi:stop",
            7: "mdi:hand",
            8: "mdi:snowflake",
            9: "mdi:alert-circle",
            10: "mdi:swap-horizontal",
        },
    },
    {
        "unique_id": "wersja_programu_1",
        "name": "Wersja programu 1",
        "register": 325,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "wersja_programu_2",
        "name": "Wersja programu 2",
        "register": 326,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "wersja_programu_3",
        "name": "Wersja programu 3",
        "register": 327,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "pompa_model_1",
        "name": "Pompa model 1",
        "register": 328,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "pompa_model_2",
        "name": "Pompa model 2",
        "register": 329,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "pompa_model_3",
        "name": "Pompa model 3",
        "register": 330,
        "scale": 1,
        "icon": "mdi:information",
    },
    {
        "unique_id": "moc_pobierana",
        "name": "Moc pobierana",
        "register": 333,
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
        "scale": 100,
        "icon": "mdi:flash",
    },
    {
        "unique_id": "napiecie_falownika",
        "name": "Napięcie falownika",
        "register": 334,
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "scale": 1,
        "icon": "mdi:alpha-v-circle",
    },
    {
        "unique_id": "prad_falownika",
        "name": "Prąd falownika",
        "register": 335,
        "unit": "A",
        "device_class": "current",
        "state_class": "measurement",
        "scale": 0.1,
        "icon": "mdi:alpha-a-circle",
    },
]

DATA = SENSORS
