ENTITIES = [
    {
        "name": "Grzałka karteru",
        "address": 1,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 1,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:radiator",
        "icon_off": "mdi:radiator-disabled",
    },
    {
        "name": "Auto start",
        "address": 2,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 2,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
    },
    {
        "name": "Manualne wprowadzenie parametrów BLCD",
        "address": 14,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 14,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
    },
    {
        "name": "Network EN",
        "address": 34,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 34,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
    },
    {
        "name": "Funkcja defrostu",
        "address": 36,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 36,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
    },
    {
        "name": "Funkcja czasowa Plan tygodniowy",
        "address": 38,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 38,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:timer-check",
        "icon_off": "mdi:timer-off",
    },
    {
        "name": "Funkcja czasowa Plan godzinowy",
        "address": 39,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 39,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:timer-check",
        "icon_off": "mdi:timer-off",
    },
    {
        "name": "Włączanie pompy",
        "address": 40,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 40,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False
        },
    },
    {
        "name": "Tryb CWU",
        "address": 42,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 42,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "Automatyczne przełączanie pomiędzy ogrzewaniem a chłodzeniem",
        "address": 47,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 47,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "Ambient temperature switch",
        "address": 52,
        "command_on": 1,
        "command_off": 0,
        "write_type": "coil",
        "verify": {
            "address": 52,
            "delay": 0,
            "input_type": "discrete",
            "state_on": True,
            "state_off": False,
        },
        "icon_on": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
]
