# climates.py
from __future__ import annotations
ENTITIES = [
    {
        "name": "Ogrzewanie temperatura zadana",
        "unique_id": "ogrzewanie_temperatura_zadana",
        # Ścieżka pliku modelowego (używana np. w device_info)
        "model_path": __file__,
        "temperature_unit": "C",
        "precision": 0,
        "temp_step": 1,
        "max_temp": 55,
        "min_temp": 10,
        "data_type": "uint16",
        "input_type": "holding",
        "scale": 0.1,
        "current_temp_register": 188,
        "target_temp_register": 1,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        # DODATKOWA OPCJA (jeśli kiedyś będziesz chciał):
        # możliwość zdefiniowania drugiego rejestru, który "blokuje" tryby
        # Tu zostawiamy puste, ale climate.py potrafi to obsłużyć, jeśli kiedyś
        # dodasz te pola w konkretnej encji:
        #
        # "hvac_mode_register_2": 300,          # drugi rejestr do warunku blokady
        # "hvac_mode_block_values": [0],        # jeśli reg2 w tej liście → OFF
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "preset_register": 0,
            "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
        },
    },
    {
        "name": "Chłodzenie temperatura zadana",
        "unique_id": "chlodzenie_temperatura_zadana",
        # Ścieżka pliku modelowego (używana np. w device_info)
        "model_path": __file__,
        "temperature_unit": "C",
        "precision": 0,
        "temp_step": 1,
        "max_temp": 25,
        "min_temp": 12,
        "data_type": "uint16",
        "input_type": "holding",
        "scale": 0.1,
        "current_temp_register": 188,
        "target_temp_register": 2,
        "icon_off": "mdi:radiator-off",
        "icon_cool": "mdi:snowflake",
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
    },

    {
        "name": "CWU temperatura zadana",
        "unique_id": "cwu_temperatura_zadana",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 195,
        "target_temp_register": 3,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "scale": 0.1,
        "precision": 0,
        "temp_step": 1,
        "temperature_unit": "C",
        "min_temp": 10,
        "max_temp": 55,
        "icon_heat": "mdi:bathtub-outline",
        "icon_off": "mdi:bathtub",

    },
    {
        "name": "Histereza ogrzewania i chłodzenia start",
        "unique_id": "histereza_ogrzewania_i_chlodzenia_start",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 6,
        "target_temp_register": 6,
        "hvac_modes": ["heat", "cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "cool": 0,
            "off": 2,
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "scale": 0.1,
        "precision": 0,
        "temp_step": 1,
        "temperature_unit": "C",
        "min_temp": 1,
        "max_temp": 15,
        "icon_heat": "mdi:radiator",
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:radiator-off",

    },
    {
        "name": "Histereza ogrzewania i chłodzenia stop",
        "unique_id": "histereza_ogrzewania_i_chlodzenia_stop",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 7,
        "target_temp_register": 7,
        "hvac_modes": ["heat", "cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "cool": 0,
            "off": 2,
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 0,
        "max_temp": 5,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "CWU histereza start",
        "unique_id": "cwu_histereza_start",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 4,
        "target_temp_register": 4,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 1,
        "max_temp": 15,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",

    },
    {
        "name": "CWU histereza stop",
        "unique_id": "cwu_histereza_stop",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 5,
        "target_temp_register": 5,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 0,
        "max_temp": 5,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "Chłodzenie temperatura zewnętrzna X1",
        "unique_id": "chlodzenie_temperatura_zewnetrzna_x1",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 276,
        "target_temp_register": 276,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 16,
        "max_temp": 60,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zewnętrzna X2",
        "unique_id": "chlodzenie_temperatura_zewnetrzna_x2",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 277,
        "target_temp_register": 277,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 16,
        "max_temp": 60,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zewnętrzna X3",
        "unique_id": "chlodzenie_temperatura_zewnetrzna_x3",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 278,
        "target_temp_register": 278,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 16,
        "max_temp": 60,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zewnętrzna X4",
        "unique_id": "chlodzenie_temperatura_zewnetrzna_x4",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 279,
        "target_temp_register": 279,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 16,
        "max_temp": 60,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zasilania Y1",
        "unique_id": "chlodzenie_temperatura_zasilania_y1",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 336,
        "target_temp_register": 336,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zasilania Y2",
        "unique_id": "chlodzenie_temperatura_zasilania_y2",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 288,
        "target_temp_register": 288,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zasilania Y3",
        "unique_id": "chlodzenie_temperatura_zasilania_y3",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 289,
        "target_temp_register": 289,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Chłodzenie temperatura zasilania Y4",
        "unique_id": "chlodzenie_temperatura_zasilania_y4",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 290,
        "target_temp_register": 290,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Ogrzewanie temperatura zewnętrzna X1",
        "unique_id": "ogrzewanie_temperatura_zewnetrzna_x1",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 280,
        "target_temp_register": 280,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 20,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zewnętrzna X2",
        "unique_id": "ogrzewanie_temperatura_zewnetrzna_x2",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 281,
        "target_temp_register": 281,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 20,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zewnętrzna X3",
        "unique_id": "ogrzewanie_temperatura_zewnetrzna_x3",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 282,
        "target_temp_register": 282,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 20,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zewnętrzna X4",
        "unique_id": "ogrzewanie_temperatura_zewnetrzna_4",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 283,
        "target_temp_register": 283,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 20,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zasilania Y1",
        "unique_id": "ogrzewanie_temperatura_zasilania_y1",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 291,
        "target_temp_register": 291,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zasilania Y2",
        "unique_id": "ogrzewanie_temperatura_zasilania_y2",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 292,
        "target_temp_register": 292,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zasilania Y3",
        "unique_id": "ogrzewanie_temperatura_zasilania_y3",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 293,
        "target_temp_register": 293,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Ogrzewanie temperatura zasilania Y4",
        "unique_id": "ogrzewanie_temperatura_zasilania_y4",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 337,
        "target_temp_register": 337,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "CWU temperatura zewnętrzna X1",
        "unique_id": "cwu_temperatura_zewnetrzna_x1",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 284,
        "target_temp_register": 284,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 50,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zewnętrzna X2",
        "unique_id": "cwu_temperatura_zewnetrzna_x2",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 285,
        "target_temp_register": 285,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 50,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zewnętrzna X3",
        "unique_id": "cwu_temperatura_zewnetrzna_x3",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 286,
        "target_temp_register": 286,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 50,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zewnętrzna X4",
        "unique_id": "cwu_temperatura_zewnetrzna_x4",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 287,
        "target_temp_register": 287,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -50,
        "max_temp": 50,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zasilania Y1",
        "unique_id": "cwu_temperatura_zasilania_y1",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 294,
        "target_temp_register": 294,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 10,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zasilania Y2",
        "unique_id": "cwu_temperatura_zasilania_y2",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 295,
        "target_temp_register": 295,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 10,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zasilania Y3",
        "unique_id": "cwu_temperatura_zasilania_y3",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 296,
        "target_temp_register": 296,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 10,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "CWU temperatura zasilania Y4",
        "unique_id": "cwu_temperatura_zasilania_y4",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 297,
        "target_temp_register": 297,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 2,
            "off": [0, 1],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 10,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:bathtub",
        "icon_off": "mdi:bathtub-outline",
    },
    {
        "name": "Funkcja czasowa temperatura chłodzenia X1",
        "unique_id": "funkcja_czasowa_temperatura_chlodzenia_x1",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 248,
        "target_temp_register": 248,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Funkcja czasowa temperatura ogrzewania X1",
        "unique_id": "funkcja_czasowa_temperatura_ogrzewania_x1",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 249,
        "target_temp_register": 249,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Funkcja czasowa temperatura chłodzenia X2",
        "unique_id": "funkcja_czasowa_temperatura_chlodzenia_x2",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 252,
        "target_temp_register": 252,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Funkcja czasowa temperatura ogrzewania X2",
        "unique_id": "funkcja_czasowa_temperatura_ogrzewania_x2",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 253,
        "target_temp_register": 253,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Funkcja czasowa temperatura chłodzenia X3",
        "unique_id": "funkcja_czasowa_temperatura_chlodzenia_x3",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 256,
        "target_temp_register": 256,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Funkcja czasowa temperatura ogrzewania X3",
        "unique_id": "funkcja_czasowa_temperatura_ogrzewania_x3",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 257,
        "target_temp_register": 257,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Funkcja czasowa temperatura chłodzenia X4",
        "unique_id": "funkcja_czasowa_temperatura_chlodzenia_x4",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 260,
        "target_temp_register": 260,
        "hvac_modes": ["cool", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "cool": 0,
            "off": [1, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 7,
        "max_temp": 18,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_cool": "mdi:snowflake",
        "icon_off": "mdi:snowflake-off",
    },
    {
        "name": "Funkcja czasowa temperatura ogrzewania X4",
        "unique_id": "funkcja_czasowa_temperatura_ogrzewania_x4",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 261,
        "target_temp_register": 261,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": 1,
            "off": [0, 2],
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": 15,
        "max_temp": 55,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:radiator",
        "icon_off": "mdi:radiator-off",
    },
    {
        "name": "Temperatura załączenia grzałki",
        "unique_id": "temperatura_zalaczenia_grzalki",
        "model_path": __file__,
        "data_type": "int16",
        "input_type": "holding",
        "current_temp_register": 14,
        "target_temp_register": 14,
        "hvac_modes": ["heat", "off"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": [1, 2],
            "off": 0,
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "hide_temp_when_off": True,
        "disable_slider_when_off": True,
        "temperature_unit": "C",
        "min_temp": -30,
        "max_temp": 20,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
        "icon_heat": "mdi:heating-coil",
        "icon_off": "mdi:heating-coil",

    },
    {
        "name": "Delta T",
        "unique_id": "delta_t",
        "model_path": __file__,
        "data_type": "uint16",
        "input_type": "holding",
        "current_temp_register": 15,
        "target_temp_register": 15,
        "hvac_modes": ["heat", "cool"],
        "hvac_mode_register": 215,
        "hvac_mode_values": {
            "heat": [1, 2],
            "cool": 0,
        },
        "preset_register": 0,
        "preset_values": {
            "Chłodzenie": 0,
            "Ogrzewanie": 1,
            "CWU": 2,
            "Chłodzenie+CWU": 3,
            "Ogrzewanie+CWU": 4,
            },
        "temperature_unit": "C",
        "min_temp": 2,
        "max_temp": 15,
        "temp_step": 1,
        "scale": 0.1,
        "precision": 0,
    },

]
